using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Web;
namespace ClearGuard {
 public static class ReportExport {
  private static string H(string text){return HttpUtility.HtmlEncode(text??"");}
  private static string C(string text){text=text??"";if(text.Length>0&&"=+-@\t\r\n".IndexOf(text[0])>=0)text="'"+text;return "\""+text.Replace("\"","\"\"")+"\"";}
  private static string Start(string title){return "<!doctype html><html lang='fa' dir='rtl'><meta charset='utf-8'><meta name='viewport' content='width=device-width'><title>"+H(title)+"</title><style>body{background:#101820;color:#f1f7f8;font:16px Segoe UI,Tahoma,sans-serif;max-width:1400px;margin:40px auto;padding:0 24px}h1{color:#59e3c0}table{width:100%;border-collapse:collapse;background:#17242f}td,th{padding:14px;border-bottom:1px solid #33444f;text-align:right;vertical-align:top}small,p{color:#b3c5ce}code{direction:ltr;display:block;overflow-wrap:anywhere;font-size:13px}th{color:#59e3c0}aside{background:#223440;border-radius:14px;padding:20px;margin:24px 0}</style><h1>"+H(title)+"</h1>";}
  public static void Scan(string path,ScanResult r){StringBuilder b=new StringBuilder(Start("ClearGuard · گزارش اسکن"));b.Append("<p>زمان: "+r.CompletedUtc.ToLocalTime().ToString("yyyy/MM/dd HH:mm:ss")+" · فقط اسکن؛ هیچ حذف خودکاری انجام نشده است.</p><aside>قابل پاک‌سازی مجاز: "+Format.Bytes(r.Rows.Where(x=>x.Eligible).Sum(x=>x.SafeBytes))+"<br>نیازمند تصمیم / محافظت: "+Format.Bytes(r.Rows.Where(x=>!x.Eligible&&x.Category!="LargeFile").Sum(x=>x.Bytes))+"<br>فضای آزاد قبل: "+Format.Bytes(r.FreeBefore)+"<br>ردیف‌های LargeFile جزئیات زیرمجموعهٔ پوشه‌ها هستند؛ در جمع محافظت دوباره شمرده نمی‌شوند. این جمع اندازهٔ کل درایو نیست.</aside>");b.Append("<h2>۱۰ مورد بزرگ‌تر</h2><ol>");foreach(ScanRow row in r.Rows.OrderByDescending(x=>x.Bytes).Take(10))b.Append("<li>"+H(row.Name)+" · "+row.Bytes.ToString("N0")+" bytes<code>"+H(row.Path)+"</code></li>");b.Append("</ol><h2>تمام موارد</h2><table><tr><th>مورد / برنامه</th><th>مسیر</th><th>حجم دقیق</th><th>وضعیت</th><th>اثر و شرط</th></tr>");foreach(ScanRow row in r.Rows.OrderByDescending(x=>x.Bytes)){b.Append("<tr><td>"+H(row.Name)+"<br>"+H(row.App)+"</td><td><code>"+H(row.Path)+"</code></td><td>"+row.Bytes.ToString("N0")+" B<br>مجاز: "+row.SafeBytes.ToString("N0")+" B</td><td>"+H(row.Status)+"</td><td>"+H(row.Effect)+"<br>"+H(row.BlockReason)+"<code>"+H(row.Keeper)+"</code></td></tr>");}b.Append("</table><h2>محدودیت‌ها / هشدارها</h2><ul>");foreach(string warn in r.Warnings)b.Append("<li>"+H(warn)+"</li>");b.Append("</ul></html>");File.WriteAllText(path,b.ToString(),new UTF8Encoding(false));}
  public static void Operation(string path,OperationReport r){StringBuilder b=new StringBuilder(Start("ClearGuard · رسید عملیات"));string mode=r.Permanent?"حذف دائمی؛ غیرقابل بازگردانی":(r.Kind??"").StartsWith("organize")?"دسته‌بندی / بازگردانی روی همان درایو؛ فایل موجود بازنویسی نشده است.":(r.Kind??"").IndexOf("restore",StringComparison.OrdinalIgnoreCase)>=0?"بازیابی موارد همین رسید؛ بدون بازنویسی.":"سطل زباله تخلیه نشده؛ انتقال به سطل به‌تنهایی فضا آزاد نمی‌کند.";b.Append("<aside>شناسه: "+H(r.Id)+"<br>حجم دقیق پردازش‌شده: "+r.ProcessedBytes.ToString("N0")+" bytes<br>فضای آزاد قبل: "+r.FreeBefore.ToString("N0")+" bytes<br>بعد: "+r.FreeAfter.ToString("N0")+" bytes<br>تغییر واقعی: "+(r.FreeAfter-r.FreeBefore).ToString("N0")+" bytes<br>"+mode+"</aside><table><tr><th>مسیر اصلی</th><th>وضعیت</th><th>حجم</th><th>جزئیات</th></tr>");foreach(OperationEntry e in r.Entries)b.Append("<tr><td><code>"+H(e.OriginalPath)+"</code></td><td>"+H(e.Status)+"</td><td>"+e.Bytes.ToString("N0")+" B</td><td>"+H(e.Detail)+"<code>"+H(e.DestinationPath)+"</code></td></tr>");b.Append("</table></html>");File.WriteAllText(path,b.ToString(),new UTF8Encoding(false));}
  public static void Csv(string path,ScanResult r){StringBuilder b=new StringBuilder("Name,Path,Bytes,SafeBytes,Application,Status,Effect,Reason,Keeper\r\n");foreach(ScanRow row in r.Rows.OrderByDescending(x=>x.Bytes))b.Append(String.Join(",",new[]{row.Name,row.Path,row.Bytes.ToString(),row.SafeBytes.ToString(),row.App,row.Status,row.Effect,row.BlockReason,row.Keeper}.Select(C))+"\r\n");File.WriteAllText(path,b.ToString(),new UTF8Encoding(true));}
 }
}
